### ISSUE TITLE
US AQI Calculation

### ISSUE THREAD

**Issue by bailes77** [Mavrrick/Hubitat-by-Mavrrick#1]
US AQI calculation incorrectly includes TVOC. Here is reference doc:
https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf

**Comment by Mavrrick** [comment]
I have updated the driver to follow the equations in that document. 

TVOC is not part of any of the US standards, so it was simply removed. I may look at adding NoX  values into the mix though, but this would require the SGH41 sensor from Air Gradient which is an addon. It looks like that is what the old math was kind of intended to emulate, but incorrectly. This also creates a need to compare the two and choose the most relevant AQI value since they don't stack, but the worst value is used.
